16-Sep-24 20:21:13: INFO: ðŸŒ± Live trader initiated
16-Sep-24 20:21:15: INFO: Websocket connected
16-Sep-24 20:21:17: INFO: CTB: Initial positions: None
16-Sep-24 20:26:17: INFO: CTB: ðŸ’° Total session PnL 0.00
16-Sep-24 20:31:18: INFO: CTB: ðŸ’° Total session PnL 0.00
16-Sep-24 20:36:19: INFO: CTB: ðŸ’° Total session PnL 0.00
16-Sep-24 20:41:20: INFO: CTB: ðŸ’° Total session PnL 0.00
16-Sep-24 20:46:21: INFO: CTB: ðŸ’° Total session PnL 0.00
16-Sep-24 21:03:29: ERROR: Traceback (most recent call last):
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 511, in setSock
    dispatcher.read(self.sock.sock, read, check)
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 115, in read
    check_callback()
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 576, in check
    raise WebSocketTimeoutException("ping/pong timed out")
websocket._exceptions.WebSocketTimeoutException: ping/pong timed out

16-Sep-24 21:03:30: ERROR: ping/pong timed out - goodbye
16-Sep-24 21:03:34: INFO: websocket closed
16-Sep-24 21:03:36: INFO: None
16-Sep-24 21:03:37: INFO: Clearing order socket ready
16-Sep-24 21:03:38: INFO: Reconnecting Kraken_orders_socket after 5 sec
16-Sep-24 21:03:46: INFO: Websocket connected
16-Sep-24 21:05:56: INFO: CTB: ðŸ’° Total session PnL 0.00
16-Sep-24 21:10:56: INFO: CTB: ðŸ’° Total session PnL 0.00
16-Sep-24 21:16:30: INFO: CTB: ðŸ’° Total session PnL 0.00
16-Sep-24 21:16:30: ERROR: Traceback (most recent call last):
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 511, in setSock
    dispatcher.read(self.sock.sock, read, check)
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 115, in read
    check_callback()
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 576, in check
    raise WebSocketTimeoutException("ping/pong timed out")
websocket._exceptions.WebSocketTimeoutException: ping/pong timed out

16-Sep-24 21:16:33: ERROR: ping/pong timed out - goodbye
16-Sep-24 21:16:38: INFO: websocket closed
16-Sep-24 21:16:39: INFO: None
16-Sep-24 21:16:40: INFO: Clearing order socket ready
16-Sep-24 21:16:41: INFO: Reconnecting Kraken_orders_socket after 5 sec
16-Sep-24 21:16:49: INFO: Websocket connected
16-Sep-24 21:35:28: ERROR: Traceback (most recent call last):
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 511, in setSock
    dispatcher.read(self.sock.sock, read, check)
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 115, in read
    check_callback()
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 576, in check
    raise WebSocketTimeoutException("ping/pong timed out")
websocket._exceptions.WebSocketTimeoutException: ping/pong timed out

16-Sep-24 21:35:29: ERROR: ping/pong timed out - goodbye
16-Sep-24 21:35:30: INFO: websocket closed
16-Sep-24 21:35:31: INFO: None
16-Sep-24 21:35:32: INFO: Clearing order socket ready
16-Sep-24 21:35:33: INFO: Reconnecting Kraken_orders_socket after 5 sec
16-Sep-24 21:35:41: INFO: Websocket connected
16-Sep-24 21:38:20: ERROR: Traceback (most recent call last):
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 511, in setSock
    dispatcher.read(self.sock.sock, read, check)
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 115, in read
    check_callback()
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 576, in check
    raise WebSocketTimeoutException("ping/pong timed out")
websocket._exceptions.WebSocketTimeoutException: ping/pong timed out

16-Sep-24 21:38:22: ERROR: ping/pong timed out - goodbye
16-Sep-24 21:38:26: INFO: websocket closed
16-Sep-24 21:38:27: INFO: None
16-Sep-24 21:38:29: INFO: Clearing order socket ready
16-Sep-24 21:38:30: INFO: Reconnecting Kraken_orders_socket after 5 sec
16-Sep-24 21:38:39: INFO: Websocket connected
16-Sep-24 21:39:12: INFO: CTB: ðŸ’° Total session PnL 0.00
16-Sep-24 21:44:13: INFO: CTB: ðŸ’° Total session PnL 0.00
16-Sep-24 21:49:14: INFO: CTB: ðŸ’° Total session PnL 0.00
16-Sep-24 21:53:30: ERROR: Traceback (most recent call last):
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 511, in setSock
    dispatcher.read(self.sock.sock, read, check)
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 115, in read
    check_callback()
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 576, in check
    raise WebSocketTimeoutException("ping/pong timed out")
websocket._exceptions.WebSocketTimeoutException: ping/pong timed out

16-Sep-24 21:53:32: ERROR: ping/pong timed out - goodbye
16-Sep-24 21:53:37: INFO: websocket closed
16-Sep-24 21:53:39: INFO: None
16-Sep-24 21:53:41: INFO: Clearing order socket ready
16-Sep-24 21:53:43: INFO: Reconnecting Kraken_orders_socket after 5 sec
16-Sep-24 21:54:15: INFO: CTB: ðŸ’° Total session PnL 0.00
16-Sep-24 21:54:26: INFO: Websocket connected
16-Sep-24 21:59:17: INFO: CTB: ðŸ’° Total session PnL 0.00
16-Sep-24 22:04:18: INFO: CTB: ðŸ’° Total session PnL 0.00
16-Sep-24 22:08:56: ERROR: Traceback (most recent call last):
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 511, in setSock
    dispatcher.read(self.sock.sock, read, check)
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 115, in read
    check_callback()
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 576, in check
    raise WebSocketTimeoutException("ping/pong timed out")
websocket._exceptions.WebSocketTimeoutException: ping/pong timed out

16-Sep-24 22:08:57: ERROR: ping/pong timed out - goodbye
16-Sep-24 22:09:01: INFO: websocket closed
16-Sep-24 22:09:02: INFO: None
16-Sep-24 22:09:02: INFO: Clearing order socket ready
16-Sep-24 22:09:03: INFO: Reconnecting Kraken_orders_socket after 5 sec
16-Sep-24 22:09:11: INFO: Websocket connected
16-Sep-24 22:09:19: INFO: CTB: ðŸ’° Total session PnL 0.00
16-Sep-24 22:10:52: ERROR: Traceback (most recent call last):
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 511, in setSock
    dispatcher.read(self.sock.sock, read, check)
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 115, in read
    check_callback()
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 576, in check
    raise WebSocketTimeoutException("ping/pong timed out")
websocket._exceptions.WebSocketTimeoutException: ping/pong timed out

16-Sep-24 22:10:53: ERROR: ping/pong timed out - goodbye
16-Sep-24 22:10:57: INFO: websocket closed
16-Sep-24 22:10:58: INFO: None
16-Sep-24 22:10:59: INFO: Clearing order socket ready
16-Sep-24 22:11:01: INFO: Reconnecting Kraken_orders_socket after 5 sec
16-Sep-24 22:11:09: INFO: Websocket connected
16-Sep-24 22:14:20: INFO: CTB: ðŸ’° Total session PnL 0.00
16-Sep-24 22:19:21: INFO: CTB: ðŸ’° Total session PnL 0.00
16-Sep-24 22:24:22: INFO: CTB: ðŸ’° Total session PnL 0.00
16-Sep-24 22:25:11: ERROR: Traceback (most recent call last):
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 511, in setSock
    dispatcher.read(self.sock.sock, read, check)
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 113, in read
    if not read_callback():
           ^^^^^^^^^^^^^^^
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 535, in read
    raise e
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_app.py", line 526, in read
    op_code, frame = self.sock.recv_data_frame(True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_core.py", line 437, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_core.py", line 478, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_abnf.py", line 363, in recv_frame
    self.recv_header()
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_abnf.py", line 319, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_abnf.py", line 398, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_core.py", line 563, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tungyuenlok/anaconda3/lib/python3.11/site-packages/websocket/_socket.py", line 132, in recv
    raise WebSocketConnectionClosedException("Connection to remote host was lost.")
websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.

16-Sep-24 22:25:12: ERROR: Connection to remote host was lost. - goodbye
16-Sep-24 22:25:13: INFO: websocket closed
16-Sep-24 22:25:14: INFO: None
16-Sep-24 22:25:15: INFO: Clearing order socket ready
16-Sep-24 22:25:16: INFO: Reconnecting Kraken_orders_socket after 5 sec
16-Sep-24 22:25:23: INFO: Websocket connected
